-- CREATE TABLE IF NOT EXISTS public.exchange_value
-- (
--   id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   currency_from TEXT not null,
--   currency_to TEXT not null,
--   conversion_multiple bigint not null,
--   port integer not null
-- );

insert into exchange_value(currency_from, currency_to, conversion_multiple, port) values('USD', 'INR', 65, 0);
insert into exchange_value(currency_from, currency_to, conversion_multiple, port) values('EUR', 'INR', 75, 0);
insert into exchange_value(currency_from, currency_to, conversion_multiple, port) values('AUD', 'INR', 55, 0);