CREATE TABLE IF NOT EXISTS public.exchange_value
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER,
  currency_from TEXT not null,
  currency_to TEXT not null,
  traded bigint not null,
  gained bigint not null,
  trade_date date not null
);
