CREATE TABLE IF NOT EXISTS public.exchange_value
(
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  currency_from TEXT not null,
  currency_to TEXT not null,
  conversion_multiple bigint not null,
  port integer not null
);
